// ============================================================
// KanaQuest — Japanese Language Data
// ============================================================

// --- HIRAGANA (46 basic characters) ---
const HIRAGANA = [
  { kana: 'あ', romaji: 'a' },
  { kana: 'い', romaji: 'i' },
  { kana: 'う', romaji: 'u' },
  { kana: 'え', romaji: 'e' },
  { kana: 'お', romaji: 'o' },
  { kana: 'か', romaji: 'ka' },
  { kana: 'き', romaji: 'ki' },
  { kana: 'く', romaji: 'ku' },
  { kana: 'け', romaji: 'ke' },
  { kana: 'こ', romaji: 'ko' },
  { kana: 'さ', romaji: 'sa' },
  { kana: 'し', romaji: 'shi' },
  { kana: 'す', romaji: 'su' },
  { kana: 'せ', romaji: 'se' },
  { kana: 'そ', romaji: 'so' },
  { kana: 'た', romaji: 'ta' },
  { kana: 'ち', romaji: 'chi' },
  { kana: 'つ', romaji: 'tsu' },
  { kana: 'て', romaji: 'te' },
  { kana: 'と', romaji: 'to' },
  { kana: 'な', romaji: 'na' },
  { kana: 'に', romaji: 'ni' },
  { kana: 'ぬ', romaji: 'nu' },
  { kana: 'ね', romaji: 'ne' },
  { kana: 'の', romaji: 'no' },
  { kana: 'は', romaji: 'ha' },
  { kana: 'ひ', romaji: 'hi' },
  { kana: 'ふ', romaji: 'fu' },
  { kana: 'へ', romaji: 'he' },
  { kana: 'ほ', romaji: 'ho' },
  { kana: 'ま', romaji: 'ma' },
  { kana: 'み', romaji: 'mi' },
  { kana: 'む', romaji: 'mu' },
  { kana: 'め', romaji: 'me' },
  { kana: 'も', romaji: 'mo' },
  { kana: 'や', romaji: 'ya' },
  { kana: 'ゆ', romaji: 'yu' },
  { kana: 'よ', romaji: 'yo' },
  { kana: 'ら', romaji: 'ra' },
  { kana: 'り', romaji: 'ri' },
  { kana: 'る', romaji: 'ru' },
  { kana: 'れ', romaji: 're' },
  { kana: 'ろ', romaji: 'ro' },
  { kana: 'わ', romaji: 'wa' },
  { kana: 'を', romaji: 'wo' },
  { kana: 'ん', romaji: 'n' }
];

// --- KATAKANA (46 basic characters) ---
const KATAKANA = [
  { kana: 'ア', romaji: 'a' },
  { kana: 'イ', romaji: 'i' },
  { kana: 'ウ', romaji: 'u' },
  { kana: 'エ', romaji: 'e' },
  { kana: 'オ', romaji: 'o' },
  { kana: 'カ', romaji: 'ka' },
  { kana: 'キ', romaji: 'ki' },
  { kana: 'ク', romaji: 'ku' },
  { kana: 'ケ', romaji: 'ke' },
  { kana: 'コ', romaji: 'ko' },
  { kana: 'サ', romaji: 'sa' },
  { kana: 'シ', romaji: 'shi' },
  { kana: 'ス', romaji: 'su' },
  { kana: 'セ', romaji: 'se' },
  { kana: 'ソ', romaji: 'so' },
  { kana: 'タ', romaji: 'ta' },
  { kana: 'チ', romaji: 'chi' },
  { kana: 'ツ', romaji: 'tsu' },
  { kana: 'テ', romaji: 'te' },
  { kana: 'ト', romaji: 'to' },
  { kana: 'ナ', romaji: 'na' },
  { kana: 'ニ', romaji: 'ni' },
  { kana: 'ヌ', romaji: 'nu' },
  { kana: 'ネ', romaji: 'ne' },
  { kana: 'ノ', romaji: 'no' },
  { kana: 'ハ', romaji: 'ha' },
  { kana: 'ヒ', romaji: 'hi' },
  { kana: 'フ', romaji: 'fu' },
  { kana: 'ヘ', romaji: 'he' },
  { kana: 'ホ', romaji: 'ho' },
  { kana: 'マ', romaji: 'ma' },
  { kana: 'ミ', romaji: 'mi' },
  { kana: 'ム', romaji: 'mu' },
  { kana: 'メ', romaji: 'me' },
  { kana: 'モ', romaji: 'mo' },
  { kana: 'ヤ', romaji: 'ya' },
  { kana: 'ユ', romaji: 'yu' },
  { kana: 'ヨ', romaji: 'yo' },
  { kana: 'ラ', romaji: 'ra' },
  { kana: 'リ', romaji: 'ri' },
  { kana: 'ル', romaji: 'ru' },
  { kana: 'レ', romaji: 're' },
  { kana: 'ロ', romaji: 'ro' },
  { kana: 'ワ', romaji: 'wa' },
  { kana: 'ヲ', romaji: 'wo' },
  { kana: 'ン', romaji: 'n' }
];

// --- LEVEL 2: Words ---
const WORDS = [
  { word: 'ねこ', romaji: 'neko', meaning: 'kucing' },
  { word: 'いぬ', romaji: 'inu', meaning: 'anjing' },
  { word: 'みず', romaji: 'mizu', meaning: 'air' },
  { word: 'やま', romaji: 'yama', meaning: 'gunung' },
  { word: 'かわ', romaji: 'kawa', meaning: 'sungai' },
  { word: 'うみ', romaji: 'umi', meaning: 'laut' },
  { word: 'そら', romaji: 'sora', meaning: 'langit' },
  { word: 'ほし', romaji: 'hoshi', meaning: 'bintang' },
  { word: 'つき', romaji: 'tsuki', meaning: 'bulan' },
  { word: 'ひ', romaji: 'hi', meaning: 'hari / matahari' },
  { word: 'はな', romaji: 'hana', meaning: 'bunga' },
  { word: 'き', romaji: 'ki', meaning: 'pohon' },
  { word: 'くさ', romaji: 'kusa', meaning: 'rumput' },
  { word: 'いし', romaji: 'ishi', meaning: 'batu' },
  { word: 'かぜ', romaji: 'kaze', meaning: 'angin' },
  { word: 'あめ', romaji: 'ame', meaning: 'hujan' },
  { word: 'ゆき', romaji: 'yuki', meaning: 'salju' },
  { word: 'ひと', romaji: 'hito', meaning: 'orang' },
  { word: 'おとこ', romaji: 'otoko', meaning: 'laki-laki' },
  { word: 'おんな', romaji: 'onna', meaning: 'perempuan' },
  { word: 'こども', romaji: 'kodomo', meaning: 'anak-anak' },
  { word: 'ともだち', romaji: 'tomodachi', meaning: 'teman' },
  { word: 'せんせい', romaji: 'sensei', meaning: 'guru' },
  { word: 'がくせい', romaji: 'gakusei', meaning: 'pelajar' },
  { word: 'しごと', romaji: 'shigoto', meaning: 'pekerjaan' },
  { word: 'いえ', romaji: 'ie', meaning: 'rumah' },
  { word: 'まち', romaji: 'machi', meaning: 'kota' },
  { word: 'くに', romaji: 'kuni', meaning: 'negara' },
  { word: 'ほん', romaji: 'hon', meaning: 'buku' },
  { word: 'えんぴつ', romaji: 'enpitsu', meaning: 'pensil' },
  { word: 'かみ', romaji: 'kami', meaning: 'kertas' },
  { word: 'くるま', romaji: 'kuruma', meaning: 'mobil' },
  { word: 'でんしゃ', romaji: 'densha', meaning: 'kereta' },
  { word: 'ひこうき', romaji: 'hikouki', meaning: 'pesawat' },
  { word: 'たべもの', romaji: 'tabemono', meaning: 'makanan' },
  { word: 'のみもの', romaji: 'nomimono', meaning: 'minuman' },
  { word: 'ごはん', romaji: 'gohan', meaning: 'nasi' },
  { word: 'さかな', romaji: 'sakana', meaning: 'ikan' },
  { word: 'にく', romaji: 'niku', meaning: 'daging' },
  { word: 'くだもの', romaji: 'kudamono', meaning: 'buah-buahan' },
  { word: 'やさい', romaji: 'yasai', meaning: 'sayuran' },
  { word: 'おちゃ', romaji: 'ocha', meaning: 'teh' },
  { word: 'あさ', romaji: 'asa', meaning: 'pagi' },
  { word: 'ひる', romaji: 'hiru', meaning: 'siang' },
  { word: 'よる', romaji: 'yoru', meaning: 'malam' },
  { word: 'きょう', romaji: 'kyou', meaning: 'hari ini' },
  { word: 'あした', romaji: 'ashita', meaning: 'besok' },
  { word: 'きのう', romaji: 'kinou', meaning: 'kemarin' },
  { word: 'おかね', romaji: 'okane', meaning: 'uang' },
  { word: 'でんわ', romaji: 'denwa', meaning: 'telepon' },
  { word: 'とけい', romaji: 'tokei', meaning: 'jam' },
  { word: 'めがね', romaji: 'megane', meaning: 'kacamata' },
  { word: 'かばん', romaji: 'kaban', meaning: 'tas' },
  { word: 'くつ', romaji: 'kutsu', meaning: 'sepatu' },
  { word: 'ふく', romaji: 'fuku', meaning: 'baju' },
  { word: 'かお', romaji: 'kao', meaning: 'wajah' },
  { word: 'あたま', romaji: 'atama', meaning: 'kepala' },
  { word: 'て', romaji: 'te', meaning: 'tangan' },
  { word: 'あし', romaji: 'ashi', meaning: 'kaki' },
  { word: 'め', romaji: 'me', meaning: 'mata' },
  { word: 'みみ', romaji: 'mimi', meaning: 'telinga' },
  { word: 'くち', romaji: 'kuchi', meaning: 'mulut' },
  { word: 'こころ', romaji: 'kokoro', meaning: 'hati' },
  { word: 'なまえ', romaji: 'namae', meaning: 'nama' },
  { word: 'にほん', romaji: 'nihon', meaning: 'Jepang' },
  { word: 'あか', romaji: 'aka', meaning: 'merah' },
  { word: 'あお', romaji: 'ao', meaning: 'biru' },
  { word: 'しろ', romaji: 'shiro', meaning: 'putih' },
  { word: 'くろ', romaji: 'kuro', meaning: 'hitam' },
  { word: 'みどり', romaji: 'midori', meaning: 'hijau' },
  { word: 'おおきい', romaji: 'ookii', meaning: 'besar' },
  { word: 'ちいさい', romaji: 'chiisai', meaning: 'kecil' },
  { word: 'あたらしい', romaji: 'atarashii', meaning: 'baru' },
  { word: 'ふるい', romaji: 'furui', meaning: 'lama' },
  { word: 'いい', romaji: 'ii', meaning: 'baik' },
  { word: 'わるい', romaji: 'warui', meaning: 'buruk' },
  { word: 'あつい', romaji: 'atsui', meaning: 'panas' },
  { word: 'さむい', romaji: 'samui', meaning: 'dingin (cuaca)' },
  { word: 'つめたい', romaji: 'tsumetai', meaning: 'dingin (benda)' },
  { word: 'たかい', romaji: 'takai', meaning: 'tinggi / mahal' },
  { word: 'ひくい', romaji: 'hikui', meaning: 'rendah' },
  { word: 'やすい', romaji: 'yasui', meaning: 'murah' },
  { word: 'はやい', romaji: 'hayai', meaning: 'cepat' },
  { word: 'おそい', romaji: 'osoi', meaning: 'lambat' },
  { word: 'おいしい', romaji: 'oishii', meaning: 'enak' },
  { word: 'まずい', romaji: 'mazui', meaning: 'tidak enak' },
  { word: 'たのしい', romaji: 'tanoshii', meaning: 'menyenangkan' },
  { word: 'つまらない', romaji: 'tsumaranai', meaning: 'membosankan' },
  { word: 'いそがしい', romaji: 'isogashii', meaning: 'sibuk' },
  { word: 'ひま', romaji: 'hima', meaning: 'luang' },
  { word: 'いく', romaji: 'iku', meaning: 'pergi' },
  { word: 'くる', romaji: 'kuru', meaning: 'datang' },
  { word: 'みる', romaji: 'miru', meaning: 'melihat' },
  { word: 'きく', romaji: 'kiku', meaning: 'mendengar / bertanya' },
  { word: 'たべる', romaji: 'taberu', meaning: 'makan' },
  { word: 'のむ', romaji: 'nomu', meaning: 'minum' },
  { word: 'よむ', romaji: 'yomu', meaning: 'membaca' },
  { word: 'かく', romaji: 'kaku', meaning: 'menulis' },
  { word: 'はなす', romaji: 'hanasu', meaning: 'berbicara' },
  { word: 'あう', romaji: 'au', meaning: 'bertemu' },
  { word: 'かう', romaji: 'kau', meaning: 'membeli' },
  { word: 'うる', romaji: 'uru', meaning: 'menjual' },
  { word: 'まつ', romaji: 'matsu', meaning: 'menunggu' },
  { word: 'すわる', romaji: 'suwaru', meaning: 'duduk' },
  { word: 'たつ', romaji: 'tatsu', meaning: 'berdiri' },
  { word: 'あるく', romaji: 'aruku', meaning: 'berjalan' },
  { word: 'はしる', romaji: 'hashiru', meaning: 'berlari' },
  { word: 'ねる', romaji: 'neru', meaning: 'tidur' },
  { word: 'おきる', romaji: 'okiru', meaning: 'bangun' },
  { word: 'あそぶ', romaji: 'asobu', meaning: 'bermain' },
  { word: 'べんきょう', romaji: 'benkyou', meaning: 'belajar' },
  { word: 'りょうり', romaji: 'ryouri', meaning: 'memasak' },
  { word: 'そうじ', romaji: 'souji', meaning: 'bersih-bersih' },
  { word: 'せんたく', romaji: 'sentaku', meaning: 'mencuci' },
  { word: 'でぐち', romaji: 'deguchi', meaning: 'pintu keluar' },
  { word: 'いりぐち', romaji: 'iriguchi', meaning: 'pintu masuk' },
  { word: 'まど', romaji: 'mado', meaning: 'jendela' },
  { word: 'ドア', romaji: 'doa', meaning: 'pintu' },
  { word: 'へや', romaji: 'heya', meaning: 'kamar' },
  { word: 'にわ', romaji: 'niwa', meaning: 'halaman' },
  { word: 'いす', romaji: 'isu', meaning: 'kursi' },
  { word: 'つくえ', romaji: 'tsukue', meaning: 'meja' },
  { word: 'ベッド', romaji: 'beddo', meaning: 'tempat tidur' },
  { word: 'でんき', romaji: 'denki', meaning: 'listrik / lampu' },
  { word: 'テレビ', romaji: 'terebi', meaning: 'televisi' },
  { word: 'パソコン', romaji: 'pasokon', meaning: 'komputer' },
  { word: 'ラジオ', romaji: 'rajio', meaning: 'radio' },
  { word: 'カメラ', romaji: 'kamera', meaning: 'kamera' },
  { word: 'じてんしゃ', romaji: 'jitensha', meaning: 'sepeda' },
  { word: 'バス', romaji: 'basu', meaning: 'bus' },
  { word: 'タクシー', romaji: 'takushii', meaning: 'taksi' },
  { word: 'みせ', romaji: 'mise', meaning: 'toko' },
  { word: 'スーパー', romaji: 'suupaa', meaning: 'supermarket' },
  { word: 'びょういん', romaji: 'byouin', meaning: 'rumah sakit' },
  { word: 'えき', romaji: 'eki', meaning: 'stasiun' },
  { word: 'こうえん', romaji: 'kouen', meaning: 'taman' },
  { word: 'がっこう', romaji: 'gakkou', meaning: 'sekolah' },
  { word: 'としょかん', romaji: 'toshokan', meaning: 'perpustakaan' },
  { word: 'ぎんこう', romaji: 'ginkou', meaning: 'bank' },
  { word: 'ゆうびんきょく', romaji: 'yuubinkyoku', meaning: 'kantor pos' },
  { word: 'みぎ', romaji: 'migi', meaning: 'kanan' },
  { word: 'ひだり', romaji: 'hidari', meaning: 'kiri' },
  { word: 'まえ', romaji: 'mae', meaning: 'depan' },
  { word: 'うしろ', romaji: 'ushiro', meaning: 'belakang' },
  { word: 'なか', romaji: 'naka', meaning: 'dalam' },
  { word: 'そと', romaji: 'soto', meaning: 'luar' },
  { word: 'ちかく', romaji: 'chikaku', meaning: 'dekat' },
  { word: 'とおい', romaji: 'tooi', meaning: 'jauh' },
  { word: 'となり', romaji: 'tonari', meaning: 'sebelah' },
  { word: 'あいだ', romaji: 'aida', meaning: 'di antara' },
  { word: 'いつ', romaji: 'itsu', meaning: 'kapan' },
  { word: 'どこ', romaji: 'doko', meaning: 'di mana' },
  { word: 'だれ', romaji: 'dare', meaning: 'siapa' },
  { word: 'なに', romaji: 'nani', meaning: 'apa' },
  { word: 'どう', romaji: 'dou', meaning: 'bagaimana' },
  { word: 'いくら', romaji: 'ikura', meaning: 'berapa harga' },
  { word: 'なぜ', romaji: 'naze', meaning: 'mengapa' },
  { word: 'はい', romaji: 'hai', meaning: 'ya' },
  { word: 'いいえ', romaji: 'iie', meaning: 'tidak' },
  { word: 'ありがとう', romaji: 'arigatou', meaning: 'terima kasih' },
  { word: 'すみません', romaji: 'sumimasen', meaning: 'permisi / maaf' },
  { word: 'ごめんなさい', romaji: 'gomennasai', meaning: 'maaf' },
  { word: 'こんにちは', romaji: 'konnichiwa', meaning: 'halo / selamat siang' },
  { word: 'こんばんは', romaji: 'konbanwa', meaning: 'selamat malam' },
  { word: 'おはよう', romaji: 'ohayou', meaning: 'selamat pagi' },
  { word: 'わたし', romaji: 'watashi', meaning: 'saya' },
  { word: 'あなた', romaji: 'anata', meaning: 'kamu' },
  { word: 'かれ', romaji: 'kare', meaning: 'dia (laki-laki)' },
  { word: 'かのじょ', romaji: 'kanojo', meaning: 'dia (perempuan)' },
  { word: 'わたしたち', romaji: 'watashitachi', meaning: 'kami / kita' },
  { word: 'かいしゃいん', romaji: 'kaishain', meaning: 'karyawan perusahaan' },
  { word: 'いしゃ', romaji: 'isha', meaning: 'dokter' },
  { word: 'エンジニア', romaji: 'enjinia', meaning: 'insinyur' },
  { word: 'おかあさん', romaji: 'okaasan', meaning: 'ibu' },
  { word: 'おとうさん', romaji: 'otousan', meaning: 'ayah' },
  { word: 'あね', romaji: 'ane', meaning: 'kakak perempuan' },
  { word: 'あに', romaji: 'ani', meaning: 'kakak laki-laki' },
  { word: 'いもうと', romaji: 'imouto', meaning: 'adik perempuan' },
  { word: 'おとうと', romaji: 'otouto', meaning: 'adik laki-laki' },
  { word: 'みんな', romaji: 'minna', meaning: 'semua orang' },
  { word: 'にほんご', romaji: 'nihongo', meaning: 'bahasa Jepang' },
  { word: 'えいご', romaji: 'eigo', meaning: 'bahasa Inggris' },
  { word: 'すうじ', romaji: 'suuji', meaning: 'angka' },
  { word: 'じかん', romaji: 'jikan', meaning: 'waktu' },
  { word: 'れきし', romaji: 'rekishi', meaning: 'sejarah' },
  { word: 'ちり', romaji: 'chiri', meaning: 'geografi' },
  { word: 'すうがく', romaji: 'suugaku', meaning: 'matematika' },
  { word: 'ぶつり', romaji: 'butsuri', meaning: 'fisika' },
  { word: 'かがく', romaji: 'kagaku', meaning: 'kimia / sains' },
  { word: 'せいぶつ', romaji: 'seibutsu', meaning: 'biologi' },
  { word: 'たいそう', romaji: 'taisou', meaning: 'olahraga' },
  { word: 'おんがく', romaji: 'ongaku', meaning: 'musik' },
  { word: 'びじゅつ', romaji: 'bijutsu', meaning: 'seni rupa' },
  { word: 'えいが', romaji: 'eiga', meaning: 'film' },
  { word: 'ざっし', romaji: 'zasshi', meaning: 'majalah' },
  { word: 'しんぶん', romaji: 'shinbun', meaning: 'koran' },
  { word: 'ノート', romaji: 'nooto', meaning: 'buku catatan' },
  { word: 'ペン', romaji: 'pen', meaning: 'pena' },
  { word: 'けしゴム', romaji: 'keshigomu', meaning: 'penghapus' },
  { word: 'かさ', romaji: 'kasa', meaning: 'payung' },
  { word: 'メール', romaji: 'meeru', meaning: 'email' },
  { word: 'ウェブサイト', romaji: 'uebusaito', meaning: 'website' },
  { word: 'アプリ', romaji: 'apuri', meaning: 'aplikasi' },
  { word: 'ゲーム', romaji: 'geemu', meaning: 'permainan' },
  { word: 'クラス', romaji: 'kurasu', meaning: 'kelas' },
  { word: 'しゅくだい', romaji: 'shukudai', meaning: 'pekerjaan rumah' },
  { word: 'テスト', romaji: 'tesuto', meaning: 'tes' },
  { word: 'しけん', romaji: 'shiken', meaning: 'ujian' },
  { word: 'せいせき', romaji: 'seiseki', meaning: 'nilai / hasil' },
  { word: 'じかんわり', romaji: 'jikawari', meaning: 'jadwal' },
  { word: 'きょうしつ', romaji: 'kyoushitsu', meaning: 'ruang kelas' }
];

// --- LEVEL 3: Sentences (35 sentences) ---
const SENTENCES = [
  { sentence: 'わたしはがくせいです', romaji: 'watashi wa gakusei desu', meaning: 'Saya adalah pelajar' },
  { sentence: 'これはほんです', romaji: 'kore wa hon desu', meaning: 'Ini adalah buku' },
  { sentence: 'おはようございます', romaji: 'ohayou gozaimasu', meaning: 'Selamat pagi' },
  { sentence: 'こんにちは', romaji: 'konnichiwa', meaning: 'Selamat siang' },
  { sentence: 'こんばんは', romaji: 'konbanwa', meaning: 'Selamat malam' },
  { sentence: 'ありがとうございます', romaji: 'arigatou gozaimasu', meaning: 'Terima kasih' },
  { sentence: 'すみません', romaji: 'sumimasen', meaning: 'Maaf / Permisi' },
  { sentence: 'おなまえはなんですか', romaji: 'onamae wa nan desu ka', meaning: 'Siapa nama Anda?' },
  { sentence: 'にほんごをべんきょうしています', romaji: 'nihongo wo benkyou shite imasu', meaning: 'Saya sedang belajar bahasa Jepang' },
  { sentence: 'いただきます', romaji: 'itadakimasu', meaning: 'Selamat makan (sebelum makan)' },
  { sentence: 'ごちそうさまでした', romaji: 'gochisousama deshita', meaning: 'Terima kasih atas makanannya' },
  { sentence: 'おげんきですか', romaji: 'ogenki desu ka', meaning: 'Apa kabar?' },
  { sentence: 'はいげんきです', romaji: 'hai genki desu', meaning: 'Ya, saya baik-baik saja' },
  { sentence: 'さようなら', romaji: 'sayounara', meaning: 'Selamat tinggal' },
  { sentence: 'がんばってください', romaji: 'ganbatte kudasai', meaning: 'Semangat!' },
  { sentence: 'わたしはにほんじんです', romaji: 'watashi wa nihonjin desu', meaning: 'Saya orang Jepang' },
  { sentence: 'これはいくらですか', romaji: 'kore wa ikura desu ka', meaning: 'Berapa harga ini?' },
  { sentence: 'トイレはどこですか', romaji: 'toire wa doko desu ka', meaning: 'Di mana toilet?' },
  { sentence: 'みずをください', romaji: 'mizu wo kudasai', meaning: 'Tolong beri air' },
  { sentence: 'にほんごがすきです', romaji: 'nihongo ga suki desu', meaning: 'Saya suka bahasa Jepang' },
  { sentence: 'たなかさんはせんせいです', romaji: 'tanaka san wa sensei desu', meaning: 'Tanaka adalah guru' },
  { sentence: 'まいにちべんきょうします', romaji: 'mainichi benkyou shimasu', meaning: 'Saya belajar setiap hari' },
  { sentence: 'あしたがっこうにいきます', romaji: 'ashita gakkou ni ikimasu', meaning: 'Besok saya pergi ke sekolah' },
  { sentence: 'ともだちとあそびます', romaji: 'tomodachi to asobimasu', meaning: 'Bermain dengan teman' },
  { sentence: 'ねこがすきです', romaji: 'neko ga suki desu', meaning: 'Saya suka kucing' },
  { sentence: 'さむいですね', romaji: 'samui desu ne', meaning: 'Dingin ya' },
  { sentence: 'あついですね', romaji: 'atsui desu ne', meaning: 'Panas ya' },
  { sentence: 'おいしいです', romaji: 'oishii desu', meaning: 'Enak' },
  { sentence: 'たのしいです', romaji: 'tanoshii desu', meaning: 'Menyenangkan' },
  { sentence: 'わたしのかぞくはよにんです', romaji: 'watashi no kazoku wa yonin desu', meaning: 'Keluarga saya empat orang' },
  { sentence: 'えいがをみます', romaji: 'eiga wo mimasu', meaning: 'Menonton film' },
  { sentence: 'おんがくをききます', romaji: 'ongaku wo kikimasu', meaning: 'Mendengarkan musik' },
  { sentence: 'ごはんをたべます', romaji: 'gohan wo tabemasu', meaning: 'Makan nasi' },
  { sentence: 'おちゃをのみます', romaji: 'ocha wo nomimasu', meaning: 'Minum teh' },
  { sentence: 'はじめまして', romaji: 'hajimemashite', meaning: 'Salam kenal' }
];

// --- LEVEL 3.1: Kanji (200 basic kanji) ---
const KANJI = [
  { kanji: '一', meaning: 'satu', onyomi: 'イチ', kunyomi: 'ひと(つ)' },
  { kanji: '二', meaning: 'dua', onyomi: 'ニ', kunyomi: 'ふた(つ)' },
  { kanji: '三', meaning: 'tiga', onyomi: 'サン', kunyomi: 'み(つ)' },
  { kanji: '四', meaning: 'empat', onyomi: 'シ', kunyomi: 'よ(つ)' },
  { kanji: '五', meaning: 'lima', onyomi: 'ゴ', kunyomi: 'いつ(つ)' },
  { kanji: '六', meaning: 'enam', onyomi: 'ロク', kunyomi: 'む(つ)' },
  { kanji: '七', meaning: 'tujuh', onyomi: 'シチ', kunyomi: 'なな(つ)' },
  { kanji: '八', meaning: 'delapan', onyomi: 'ハチ', kunyomi: 'や(つ)' },
  { kanji: '九', meaning: 'sembilan', onyomi: 'キュウ', kunyomi: 'ここの(つ)' },
  { kanji: '十', meaning: 'sepuluh', onyomi: 'ジュウ', kunyomi: 'とお' },
  { kanji: '百', meaning: 'seratus', onyomi: 'ヒャク', kunyomi: '' },
  { kanji: '千', meaning: 'seribu', onyomi: 'セン', kunyomi: 'ち' },
  { kanji: '万', meaning: 'sepuluh ribu', onyomi: 'マン', kunyomi: '' },
  { kanji: '円', meaning: 'yen / lingkaran', onyomi: 'エン', kunyomi: 'まる' },
  { kanji: '日', meaning: 'hari / matahari', onyomi: 'ニチ', kunyomi: 'ひ' },
  { kanji: '月', meaning: 'bulan', onyomi: 'ゲツ', kunyomi: 'つき' },
  { kanji: '火', meaning: 'api', onyomi: 'カ', kunyomi: 'ひ' },
  { kanji: '水', meaning: 'air', onyomi: 'スイ', kunyomi: 'みず' },
  { kanji: '木', meaning: 'pohon', onyomi: 'モク', kunyomi: 'き' },
  { kanji: '金', meaning: 'emas / uang', onyomi: 'キン', kunyomi: 'かね' },
  { kanji: '土', meaning: 'tanah', onyomi: 'ド', kunyomi: 'つち' },
  { kanji: '人', meaning: 'orang', onyomi: 'ジン', kunyomi: 'ひと' },
  { kanji: '子', meaning: 'anak', onyomi: 'シ', kunyomi: 'こ' },
  { kanji: '女', meaning: 'perempuan', onyomi: 'ジョ', kunyomi: 'おんな' },
  { kanji: '男', meaning: 'laki-laki', onyomi: 'ダン', kunyomi: 'おとこ' },
  { kanji: '大', meaning: 'besar', onyomi: 'ダイ', kunyomi: 'おお(きい)' },
  { kanji: '小', meaning: 'kecil', onyomi: 'ショウ', kunyomi: 'ちい(さい)' },
  { kanji: '中', meaning: 'tengah', onyomi: 'チュウ', kunyomi: 'なか' },
  { kanji: '上', meaning: 'atas', onyomi: 'ジョウ', kunyomi: 'うえ' },
  { kanji: '下', meaning: 'bawah', onyomi: 'カ', kunyomi: 'した' },
  { kanji: '左', meaning: 'kiri', onyomi: 'サ', kunyomi: 'ひだり' },
  { kanji: '右', meaning: 'kanan', onyomi: 'ウ', kunyomi: 'みぎ' },
  { kanji: '山', meaning: 'gunung', onyomi: 'サン', kunyomi: 'やま' },
  { kanji: '川', meaning: 'sungai', onyomi: 'セン', kunyomi: 'かわ' },
  { kanji: '田', meaning: 'sawah', onyomi: 'デン', kunyomi: 'た' },
  { kanji: '森', meaning: 'hutan', onyomi: 'シン', kunyomi: 'もり' },
  { kanji: '林', meaning: 'hutan kecil', onyomi: 'リン', kunyomi: 'はやし' },
  { kanji: '花', meaning: 'bunga', onyomi: 'カ', kunyomi: 'はな' },
  { kanji: '草', meaning: 'rumput', onyomi: 'ソウ', kunyomi: 'くさ' },
  { kanji: '石', meaning: 'batu', onyomi: 'セキ', kunyomi: 'いし' },
  { kanji: '空', meaning: 'langit / kosong', onyomi: 'クウ', kunyomi: 'そら' },
  { kanji: '天', meaning: 'langit / surga', onyomi: 'テン', kunyomi: 'あま' },
  { kanji: '気', meaning: 'udara / semangat', onyomi: 'キ', kunyomi: '' },
  { kanji: '雨', meaning: 'hujan', onyomi: 'ウ', kunyomi: 'あめ' },
  { kanji: '雪', meaning: 'salju', onyomi: 'セツ', kunyomi: 'ゆき' },
  { kanji: '風', meaning: 'angin', onyomi: 'フウ', kunyomi: 'かぜ' },
  { kanji: '雲', meaning: 'awan', onyomi: 'ウン', kunyomi: 'くも' },
  { kanji: '海', meaning: 'laut', onyomi: 'カイ', kunyomi: 'うみ' },
  { kanji: '池', meaning: 'kolam', onyomi: 'チ', kunyomi: 'いけ' },
  { kanji: '島', meaning: 'pulau', onyomi: 'トウ', kunyomi: 'しま' },
  { kanji: '星', meaning: 'bintang', onyomi: 'セイ', kunyomi: 'ほし' },
  { kanji: '光', meaning: 'cahaya', onyomi: 'コウ', kunyomi: 'ひかり' },
  { kanji: '目', meaning: 'mata', onyomi: 'モク', kunyomi: 'め' },
  { kanji: '耳', meaning: 'telinga', onyomi: 'ジ', kunyomi: 'みみ' },
  { kanji: '口', meaning: 'mulut', onyomi: 'コウ', kunyomi: 'くち' },
  { kanji: '手', meaning: 'tangan', onyomi: 'シュ', kunyomi: 'て' },
  { kanji: '足', meaning: 'kaki', onyomi: 'ソク', kunyomi: 'あし' },
  { kanji: '力', meaning: 'kekuatan', onyomi: 'リョク', kunyomi: 'ちから' },
  { kanji: '心', meaning: 'hati', onyomi: 'シン', kunyomi: 'こころ' },
  { kanji: '体', meaning: 'tubuh', onyomi: 'タイ', kunyomi: 'からだ' },
  { kanji: '頭', meaning: 'kepala', onyomi: 'トウ', kunyomi: 'あたま' },
  { kanji: '顔', meaning: 'wajah', onyomi: 'ガン', kunyomi: 'かお' },
  { kanji: '声', meaning: 'suara', onyomi: 'セイ', kunyomi: 'こえ' },
  { kanji: '名', meaning: 'nama', onyomi: 'メイ', kunyomi: 'な' },
  { kanji: '年', meaning: 'tahun', onyomi: 'ネン', kunyomi: 'とし' },
  { kanji: '生', meaning: 'hidup / lahir', onyomi: 'セイ', kunyomi: 'い(きる)' },
  { kanji: '死', meaning: 'mati', onyomi: 'シ', kunyomi: 'し(ぬ)' },
  { kanji: '先', meaning: 'sebelumnya / duluan', onyomi: 'セン', kunyomi: 'さき' },
  { kanji: '学', meaning: 'belajar', onyomi: 'ガク', kunyomi: 'まな(ぶ)' },
  { kanji: '校', meaning: 'sekolah', onyomi: 'コウ', kunyomi: '' },
  { kanji: '本', meaning: 'buku / asal', onyomi: 'ホン', kunyomi: 'もと' },
  { kanji: '文', meaning: 'tulisan / kalimat', onyomi: 'ブン', kunyomi: 'ふみ' },
  { kanji: '字', meaning: 'huruf', onyomi: 'ジ', kunyomi: 'あざ' },
  { kanji: '語', meaning: 'bahasa / kata', onyomi: 'ゴ', kunyomi: 'かた(る)' },
  { kanji: '読', meaning: 'membaca', onyomi: 'ドク', kunyomi: 'よ(む)' },
  { kanji: '書', meaning: 'menulis', onyomi: 'ショ', kunyomi: 'か(く)' },
  { kanji: '話', meaning: 'berbicara', onyomi: 'ワ', kunyomi: 'はな(す)' },
  { kanji: '聞', meaning: 'mendengar', onyomi: 'ブン', kunyomi: 'き(く)' },
  { kanji: '見', meaning: 'melihat', onyomi: 'ケン', kunyomi: 'み(る)' },
  { kanji: '言', meaning: 'berkata', onyomi: 'ゲン', kunyomi: 'い(う)' },
  { kanji: '食', meaning: 'makan', onyomi: 'ショク', kunyomi: 'た(べる)' },
  { kanji: '飲', meaning: 'minum', onyomi: 'イン', kunyomi: 'の(む)' },
  { kanji: '立', meaning: 'berdiri', onyomi: 'リツ', kunyomi: 'た(つ)' },
  { kanji: '休', meaning: 'istirahat', onyomi: 'キュウ', kunyomi: 'やす(む)' },
  { kanji: '入', meaning: 'masuk', onyomi: 'ニュウ', kunyomi: 'い(る)' },
  { kanji: '出', meaning: 'keluar', onyomi: 'シュツ', kunyomi: 'で(る)' },
  { kanji: '行', meaning: 'pergi', onyomi: 'コウ', kunyomi: 'い(く)' },
  { kanji: '来', meaning: 'datang', onyomi: 'ライ', kunyomi: 'く(る)' },
  { kanji: '帰', meaning: 'pulang', onyomi: 'キ', kunyomi: 'かえ(る)' },
  { kanji: '走', meaning: 'berlari', onyomi: 'ソウ', kunyomi: 'はし(る)' },
  { kanji: '歩', meaning: 'berjalan', onyomi: 'ホ', kunyomi: 'ある(く)' },
  { kanji: '車', meaning: 'mobil / kendaraan', onyomi: 'シャ', kunyomi: 'くるま' },
  { kanji: '電', meaning: 'listrik', onyomi: 'デン', kunyomi: '' },
  { kanji: '駅', meaning: 'stasiun', onyomi: 'エキ', kunyomi: '' },
  { kanji: '道', meaning: 'jalan', onyomi: 'ドウ', kunyomi: 'みち' },
  { kanji: '店', meaning: 'toko', onyomi: 'テン', kunyomi: 'みせ' },
  { kanji: '会', meaning: 'bertemu / pertemuan', onyomi: 'カイ', kunyomi: 'あ(う)' },
  { kanji: '社', meaning: 'perusahaan / kuil', onyomi: 'シャ', kunyomi: 'やしろ' },
  { kanji: '家', meaning: 'rumah / keluarga', onyomi: 'カ', kunyomi: 'いえ' },
  { kanji: '国', meaning: 'negara', onyomi: 'コク', kunyomi: 'くに' },
  { kanji: '町', meaning: 'kota kecil', onyomi: 'チョウ', kunyomi: 'まち' },
  { kanji: '村', meaning: 'desa', onyomi: 'ソン', kunyomi: 'むら' },
  { kanji: '友', meaning: 'teman', onyomi: 'ユウ', kunyomi: 'とも' },
  { kanji: '父', meaning: 'ayah', onyomi: 'フ', kunyomi: 'ちち' },
  { kanji: '母', meaning: 'ibu', onyomi: 'ボ', kunyomi: 'はは' },
  { kanji: '兄', meaning: 'kakak laki-laki', onyomi: 'ケイ', kunyomi: 'あに' },
  { kanji: '姉', meaning: 'kakak perempuan', onyomi: 'シ', kunyomi: 'あね' },
  { kanji: '弟', meaning: 'adik laki-laki', onyomi: 'テイ', kunyomi: 'おとうと' },
  { kanji: '妹', meaning: 'adik perempuan', onyomi: 'マイ', kunyomi: 'いもうと' },
  { kanji: '夫', meaning: 'suami', onyomi: 'フ', kunyomi: 'おっと' },
  { kanji: '妻', meaning: 'istri', onyomi: 'サイ', kunyomi: 'つま' },
  { kanji: '王', meaning: 'raja', onyomi: 'オウ', kunyomi: '' },
  { kanji: '犬', meaning: 'anjing', onyomi: 'ケン', kunyomi: 'いぬ' },
  { kanji: '猫', meaning: 'kucing', onyomi: 'ビョウ', kunyomi: 'ねこ' },
  { kanji: '鳥', meaning: 'burung', onyomi: 'チョウ', kunyomi: 'とり' },
  { kanji: '魚', meaning: 'ikan', onyomi: 'ギョ', kunyomi: 'さかな' },
  { kanji: '虫', meaning: 'serangga', onyomi: 'チュウ', kunyomi: 'むし' },
  { kanji: '牛', meaning: 'sapi', onyomi: 'ギュウ', kunyomi: 'うし' },
  { kanji: '馬', meaning: 'kuda', onyomi: 'バ', kunyomi: 'うま' },
  { kanji: '肉', meaning: 'daging', onyomi: 'ニク', kunyomi: '' },
  { kanji: '米', meaning: 'beras', onyomi: 'ベイ', kunyomi: 'こめ' },
  { kanji: '茶', meaning: 'teh', onyomi: 'チャ', kunyomi: '' },
  { kanji: '酒', meaning: 'sake / alkohol', onyomi: 'シュ', kunyomi: 'さけ' },
  { kanji: '色', meaning: 'warna', onyomi: 'ショク', kunyomi: 'いろ' },
  { kanji: '白', meaning: 'putih', onyomi: 'ハク', kunyomi: 'しろ' },
  { kanji: '黒', meaning: 'hitam', onyomi: 'コク', kunyomi: 'くろ' },
  { kanji: '赤', meaning: 'merah', onyomi: 'セキ', kunyomi: 'あか' },
  { kanji: '青', meaning: 'biru', onyomi: 'セイ', kunyomi: 'あお' },
  { kanji: '高', meaning: 'tinggi / mahal', onyomi: 'コウ', kunyomi: 'たか(い)' },
  { kanji: '安', meaning: 'murah / aman', onyomi: 'アン', kunyomi: 'やす(い)' },
  { kanji: '新', meaning: 'baru', onyomi: 'シン', kunyomi: 'あたら(しい)' },
  { kanji: '古', meaning: 'lama / tua', onyomi: 'コ', kunyomi: 'ふる(い)' },
  { kanji: '長', meaning: 'panjang / ketua', onyomi: 'チョウ', kunyomi: 'なが(い)' },
  { kanji: '短', meaning: 'pendek', onyomi: 'タン', kunyomi: 'みじか(い)' },
  { kanji: '多', meaning: 'banyak', onyomi: 'タ', kunyomi: 'おお(い)' },
  { kanji: '少', meaning: 'sedikit', onyomi: 'ショウ', kunyomi: 'すく(ない)' },
  { kanji: '早', meaning: 'cepat / pagi', onyomi: 'ソウ', kunyomi: 'はや(い)' },
  { kanji: '遅', meaning: 'lambat / terlambat', onyomi: 'チ', kunyomi: 'おそ(い)' },
  { kanji: '強', meaning: 'kuat', onyomi: 'キョウ', kunyomi: 'つよ(い)' },
  { kanji: '弱', meaning: 'lemah', onyomi: 'ジャク', kunyomi: 'よわ(い)' },
  { kanji: '明', meaning: 'terang / besok', onyomi: 'メイ', kunyomi: 'あか(るい)' },
  { kanji: '暗', meaning: 'gelap', onyomi: 'アン', kunyomi: 'くら(い)' },
  { kanji: '重', meaning: 'berat', onyomi: 'ジュウ', kunyomi: 'おも(い)' },
  { kanji: '軽', meaning: 'ringan', onyomi: 'ケイ', kunyomi: 'かる(い)' },
  { kanji: '広', meaning: 'luas', onyomi: 'コウ', kunyomi: 'ひろ(い)' },
  { kanji: '近', meaning: 'dekat', onyomi: 'キン', kunyomi: 'ちか(い)' },
  { kanji: '遠', meaning: 'jauh', onyomi: 'エン', kunyomi: 'とお(い)' },
  { kanji: '正', meaning: 'benar / tepat', onyomi: 'セイ', kunyomi: 'ただ(しい)' },
  { kanji: '同', meaning: 'sama', onyomi: 'ドウ', kunyomi: 'おな(じ)' },
  { kanji: '今', meaning: 'sekarang', onyomi: 'コン', kunyomi: 'いま' },
  { kanji: '前', meaning: 'depan / sebelum', onyomi: 'ゼン', kunyomi: 'まえ' },
  { kanji: '後', meaning: 'belakang / sesudah', onyomi: 'ゴ', kunyomi: 'うし(ろ)' },
  { kanji: '朝', meaning: 'pagi', onyomi: 'チョウ', kunyomi: 'あさ' },
  { kanji: '昼', meaning: 'siang', onyomi: 'チュウ', kunyomi: 'ひる' },
  { kanji: '夜', meaning: 'malam', onyomi: 'ヤ', kunyomi: 'よる' },
  { kanji: '夕', meaning: 'sore', onyomi: 'セキ', kunyomi: 'ゆう' },
  { kanji: '春', meaning: 'musim semi', onyomi: 'シュン', kunyomi: 'はる' },
  { kanji: '夏', meaning: 'musim panas', onyomi: 'カ', kunyomi: 'なつ' },
  { kanji: '秋', meaning: 'musim gugur', onyomi: 'シュウ', kunyomi: 'あき' },
  { kanji: '冬', meaning: 'musim dingin', onyomi: 'トウ', kunyomi: 'ふゆ' },
  { kanji: '東', meaning: 'timur', onyomi: 'トウ', kunyomi: 'ひがし' },
  { kanji: '西', meaning: 'barat', onyomi: 'セイ', kunyomi: 'にし' },
  { kanji: '南', meaning: 'selatan', onyomi: 'ナン', kunyomi: 'みなみ' },
  { kanji: '北', meaning: 'utara', onyomi: 'ホク', kunyomi: 'きた' },
  { kanji: '外', meaning: 'luar', onyomi: 'ガイ', kunyomi: 'そと' },
  { kanji: '内', meaning: 'dalam', onyomi: 'ナイ', kunyomi: 'うち' },
  { kanji: '間', meaning: 'antara / waktu', onyomi: 'カン', kunyomi: 'あいだ' },
  { kanji: '時', meaning: 'waktu / jam', onyomi: 'ジ', kunyomi: 'とき' },
  { kanji: '分', meaning: 'menit / bagian', onyomi: 'ブン', kunyomi: 'わ(かる)' },
  { kanji: '半', meaning: 'setengah', onyomi: 'ハン', kunyomi: 'なか(ば)' },
  { kanji: '毎', meaning: 'setiap', onyomi: 'マイ', kunyomi: '' },
  { kanji: '何', meaning: 'apa', onyomi: 'カ', kunyomi: 'なに' },
  { kanji: '数', meaning: 'angka / menghitung', onyomi: 'スウ', kunyomi: 'かず' },
  { kanji: '答', meaning: 'jawaban', onyomi: 'トウ', kunyomi: 'こた(える)' },
  { kanji: '問', meaning: 'pertanyaan', onyomi: 'モン', kunyomi: 'と(う)' },
  { kanji: '思', meaning: 'berpikir', onyomi: 'シ', kunyomi: 'おも(う)' },
  { kanji: '知', meaning: 'mengetahui', onyomi: 'チ', kunyomi: 'し(る)' },
  { kanji: '考', meaning: 'berpikir / mempertimbangkan', onyomi: 'コウ', kunyomi: 'かんが(える)' },
  { kanji: '教', meaning: 'mengajar', onyomi: 'キョウ', kunyomi: 'おし(える)' },
  { kanji: '習', meaning: 'belajar / kebiasaan', onyomi: 'シュウ', kunyomi: 'なら(う)' },
  { kanji: '使', meaning: 'menggunakan', onyomi: 'シ', kunyomi: 'つか(う)' },
  { kanji: '作', meaning: 'membuat', onyomi: 'サク', kunyomi: 'つく(る)' },
  { kanji: '動', meaning: 'bergerak', onyomi: 'ドウ', kunyomi: 'うご(く)' },
  { kanji: '止', meaning: 'berhenti', onyomi: 'シ', kunyomi: 'と(まる)' },
  { kanji: '開', meaning: 'membuka', onyomi: 'カイ', kunyomi: 'あ(ける)' },
  { kanji: '閉', meaning: 'menutup', onyomi: 'ヘイ', kunyomi: 'し(める)' },
  { kanji: '持', meaning: 'membawa / memiliki', onyomi: 'ジ', kunyomi: 'も(つ)' },
  { kanji: '待', meaning: 'menunggu', onyomi: 'タイ', kunyomi: 'ま(つ)' },
  { kanji: '送', meaning: 'mengirim', onyomi: 'ソウ', kunyomi: 'おく(る)' },
  { kanji: '買', meaning: 'membeli', onyomi: 'バイ', kunyomi: 'か(う)' },
  { kanji: '売', meaning: 'menjual', onyomi: 'バイ', kunyomi: 'う(る)' },
  { kanji: '住', meaning: 'tinggal', onyomi: 'ジュウ', kunyomi: 'す(む)' },
  { kanji: '働', meaning: 'bekerja', onyomi: 'ドウ', kunyomi: 'はたら(く)' },
  { kanji: '遊', meaning: 'bermain', onyomi: 'ユウ', kunyomi: 'あそ(ぶ)' },
  { kanji: '泳', meaning: 'berenang', onyomi: 'エイ', kunyomi: 'およ(ぐ)' },
  { kanji: '飛', meaning: 'terbang', onyomi: 'ヒ', kunyomi: 'と(ぶ)' },
  { kanji: '切', meaning: 'memotong', onyomi: 'セツ', kunyomi: 'き(る)' },
  { kanji: '洗', meaning: 'mencuci', onyomi: 'セン', kunyomi: 'あら(う)' },
  { kanji: '着', meaning: 'memakai / sampai', onyomi: 'チャク', kunyomi: 'き(る)' },
  { kanji: '起', meaning: 'bangun', onyomi: 'キ', kunyomi: 'お(きる)' },
  { kanji: '寝', meaning: 'tidur', onyomi: 'シン', kunyomi: 'ね(る)' },
  { kanji: '映', meaning: 'memantulkan / film', onyomi: 'エイ', kunyomi: 'うつ(る)' },
  { kanji: '画', meaning: 'gambar', onyomi: 'ガ', kunyomi: '' },
  { kanji: '歌', meaning: 'lagu / bernyanyi', onyomi: 'カ', kunyomi: 'うた' },
  { kanji: '音', meaning: 'suara / bunyi', onyomi: 'オン', kunyomi: 'おと' },
  { kanji: '楽', meaning: 'menyenangkan / musik', onyomi: 'ガク', kunyomi: 'たの(しい)' },
  { kanji: '紙', meaning: 'kertas', onyomi: 'シ', kunyomi: 'かみ' },
  { kanji: '料', meaning: 'bahan / biaya', onyomi: 'リョウ', kunyomi: '' },
  { kanji: '理', meaning: 'alasan / logika', onyomi: 'リ', kunyomi: '' },
  { kanji: '門', meaning: 'gerbang', onyomi: 'モン', kunyomi: 'かど' },
  { kanji: '場', meaning: 'tempat', onyomi: 'ジョウ', kunyomi: 'ば' },
  { kanji: '地', meaning: 'tanah / bumi', onyomi: 'チ', kunyomi: '' },
  { kanji: '図', meaning: 'gambar / peta', onyomi: 'ズ', kunyomi: '' },
  { kanji: '室', meaning: 'ruangan', onyomi: 'シツ', kunyomi: 'むろ' },
  { kanji: '屋', meaning: 'toko / atap', onyomi: 'オク', kunyomi: 'や' },
  { kanji: '窓', meaning: 'jendela', onyomi: 'ソウ', kunyomi: 'まど' },
  { kanji: '病', meaning: 'sakit', onyomi: 'ビョウ', kunyomi: 'やまい' },
  { kanji: '院', meaning: 'institusi', onyomi: 'イン', kunyomi: '' },
  { kanji: '医', meaning: 'dokter / medis', onyomi: 'イ', kunyomi: '' },
  { kanji: '薬', meaning: 'obat', onyomi: 'ヤク', kunyomi: 'くすり' },
  { kanji: '服', meaning: 'baju', onyomi: 'フク', kunyomi: '' },
  { kanji: '物', meaning: 'benda', onyomi: 'ブツ', kunyomi: 'もの' },
  { kanji: '事', meaning: 'hal / pekerjaan', onyomi: 'ジ', kunyomi: 'こと' },
  { kanji: '仕', meaning: 'melayani', onyomi: 'シ', kunyomi: 'つか(える)' },
  { kanji: '世', meaning: 'dunia / generasi', onyomi: 'セ', kunyomi: 'よ' },
  { kanji: '界', meaning: 'dunia / batas', onyomi: 'カイ', kunyomi: '' },
  { kanji: '部', meaning: 'bagian', onyomi: 'ブ', kunyomi: '' },
  { kanji: '員', meaning: 'anggota', onyomi: 'イン', kunyomi: '' },
  { kanji: '発', meaning: 'berangkat / mengeluarkan', onyomi: 'ハツ', kunyomi: '' },
  { kanji: '着', meaning: 'tiba / memakai', onyomi: 'チャク', kunyomi: 'つ(く)' },
  { kanji: '集', meaning: 'mengumpulkan', onyomi: 'シュウ', kunyomi: 'あつ(まる)' },
  { kanji: '園', meaning: 'taman', onyomi: 'エン', kunyomi: 'その' },
  { kanji: '特', meaning: 'khusus', onyomi: 'トク', kunyomi: '' },
  { kanji: '別', meaning: 'berbeda / khusus', onyomi: 'ベツ', kunyomi: 'わか(れる)' },
  { kanji: '度', meaning: 'derajat / kali', onyomi: 'ド', kunyomi: 'たび' },
  { kanji: '計', meaning: 'mengukur / menghitung', onyomi: 'ケイ', kunyomi: 'はか(る)' },
  { kanji: '記', meaning: 'catatan', onyomi: 'キ', kunyomi: 'しる(す)' },
  { kanji: '写', meaning: 'menyalin / foto', onyomi: 'シャ', kunyomi: 'うつ(す)' },
  { kanji: '真', meaning: 'benar / asli', onyomi: 'シン', kunyomi: 'ま' },
  { kanji: '全', meaning: 'semua / seluruh', onyomi: 'ゼン', kunyomi: 'まった(く)' },
  { kanji: '自', meaning: 'sendiri', onyomi: 'ジ', kunyomi: 'みずか(ら)' },
  { kanji: '転', meaning: 'berputar / berguling', onyomi: 'テン', kunyomi: 'ころ(がる)' },
  { kanji: '運', meaning: 'nasib / mengangkut', onyomi: 'ウン', kunyomi: 'はこ(ぶ)' },
  { kanji: '急', meaning: 'terburu-buru', onyomi: 'キュウ', kunyomi: 'いそ(ぐ)' },
  { kanji: '説', meaning: 'menjelaskan', onyomi: 'セツ', kunyomi: 'と(く)' },
  { kanji: '味', meaning: 'rasa', onyomi: 'ミ', kunyomi: 'あじ' }
];
