// ============================================================
// KanaQuest — Japanese Language Data
// ============================================================

// --- HIRAGANA (46 basic characters) ---
const HIRAGANA = [
  { kana: 'あ', romaji: 'a' },
  { kana: 'い', romaji: 'i' },
  { kana: 'う', romaji: 'u' },
  { kana: 'え', romaji: 'e' },
  { kana: 'お', romaji: 'o' },
  { kana: 'か', romaji: 'ka' },
  { kana: 'き', romaji: 'ki' },
  { kana: 'く', romaji: 'ku' },
  { kana: 'け', romaji: 'ke' },
  { kana: 'こ', romaji: 'ko' },
  { kana: 'さ', romaji: 'sa' },
  { kana: 'し', romaji: 'shi' },
  { kana: 'す', romaji: 'su' },
  { kana: 'せ', romaji: 'se' },
  { kana: 'そ', romaji: 'so' },
  { kana: 'た', romaji: 'ta' },
  { kana: 'ち', romaji: 'chi' },
  { kana: 'つ', romaji: 'tsu' },
  { kana: 'て', romaji: 'te' },
  { kana: 'と', romaji: 'to' },
  { kana: 'な', romaji: 'na' },
  { kana: 'に', romaji: 'ni' },
  { kana: 'ぬ', romaji: 'nu' },
  { kana: 'ね', romaji: 'ne' },
  { kana: 'の', romaji: 'no' },
  { kana: 'は', romaji: 'ha' },
  { kana: 'ひ', romaji: 'hi' },
  { kana: 'ふ', romaji: 'fu' },
  { kana: 'へ', romaji: 'he' },
  { kana: 'ほ', romaji: 'ho' },
  { kana: 'ま', romaji: 'ma' },
  { kana: 'み', romaji: 'mi' },
  { kana: 'む', romaji: 'mu' },
  { kana: 'め', romaji: 'me' },
  { kana: 'も', romaji: 'mo' },
  { kana: 'や', romaji: 'ya' },
  { kana: 'ゆ', romaji: 'yu' },
  { kana: 'よ', romaji: 'yo' },
  { kana: 'ら', romaji: 'ra' },
  { kana: 'り', romaji: 'ri' },
  { kana: 'る', romaji: 'ru' },
  { kana: 'れ', romaji: 're' },
  { kana: 'ろ', romaji: 'ro' },
  { kana: 'わ', romaji: 'wa' },
  { kana: 'を', romaji: 'wo' },
  { kana: 'ん', romaji: 'n' }
];

// --- KATAKANA (46 basic characters) ---
const KATAKANA = [
  { kana: 'ア', romaji: 'a' },
  { kana: 'イ', romaji: 'i' },
  { kana: 'ウ', romaji: 'u' },
  { kana: 'エ', romaji: 'e' },
  { kana: 'オ', romaji: 'o' },
  { kana: 'カ', romaji: 'ka' },
  { kana: 'キ', romaji: 'ki' },
  { kana: 'ク', romaji: 'ku' },
  { kana: 'ケ', romaji: 'ke' },
  { kana: 'コ', romaji: 'ko' },
  { kana: 'サ', romaji: 'sa' },
  { kana: 'シ', romaji: 'shi' },
  { kana: 'ス', romaji: 'su' },
  { kana: 'セ', romaji: 'se' },
  { kana: 'ソ', romaji: 'so' },
  { kana: 'タ', romaji: 'ta' },
  { kana: 'チ', romaji: 'chi' },
  { kana: 'ツ', romaji: 'tsu' },
  { kana: 'テ', romaji: 'te' },
  { kana: 'ト', romaji: 'to' },
  { kana: 'ナ', romaji: 'na' },
  { kana: 'ニ', romaji: 'ni' },
  { kana: 'ヌ', romaji: 'nu' },
  { kana: 'ネ', romaji: 'ne' },
  { kana: 'ノ', romaji: 'no' },
  { kana: 'ハ', romaji: 'ha' },
  { kana: 'ヒ', romaji: 'hi' },
  { kana: 'フ', romaji: 'fu' },
  { kana: 'ヘ', romaji: 'he' },
  { kana: 'ホ', romaji: 'ho' },
  { kana: 'マ', romaji: 'ma' },
  { kana: 'ミ', romaji: 'mi' },
  { kana: 'ム', romaji: 'mu' },
  { kana: 'メ', romaji: 'me' },
  { kana: 'モ', romaji: 'mo' },
  { kana: 'ヤ', romaji: 'ya' },
  { kana: 'ユ', romaji: 'yu' },
  { kana: 'ヨ', romaji: 'yo' },
  { kana: 'ラ', romaji: 'ra' },
  { kana: 'リ', romaji: 'ri' },
  { kana: 'ル', romaji: 'ru' },
  { kana: 'レ', romaji: 're' },
  { kana: 'ロ', romaji: 'ro' },
  { kana: 'ワ', romaji: 'wa' },
  { kana: 'ヲ', romaji: 'wo' },
  { kana: 'ン', romaji: 'n' }
];

// --- LEVEL 2: Words (65 words) ---
const WORDS = [
  { word: 'ねこ', romaji: 'neko', meaning: 'kucing' },
  { word: 'いぬ', romaji: 'inu', meaning: 'anjing' },
  { word: 'みず', romaji: 'mizu', meaning: 'air' },
  { word: 'やま', romaji: 'yama', meaning: 'gunung' },
  { word: 'かわ', romaji: 'kawa', meaning: 'sungai' },
  { word: 'うみ', romaji: 'umi', meaning: 'laut' },
  { word: 'そら', romaji: 'sora', meaning: 'langit' },
  { word: 'ほし', romaji: 'hoshi', meaning: 'bintang' },
  { word: 'つき', romaji: 'tsuki', meaning: 'bulan' },
  { word: 'ひ', romaji: 'hi', meaning: 'hari / matahari' },
  { word: 'はな', romaji: 'hana', meaning: 'bunga' },
  { word: 'き', romaji: 'ki', meaning: 'pohon' },
  { word: 'くさ', romaji: 'kusa', meaning: 'rumput' },
  { word: 'いし', romaji: 'ishi', meaning: 'batu' },
  { word: 'かぜ', romaji: 'kaze', meaning: 'angin' },
  { word: 'あめ', romaji: 'ame', meaning: 'hujan' },
  { word: 'ゆき', romaji: 'yuki', meaning: 'salju' },
  { word: 'ひと', romaji: 'hito', meaning: 'orang' },
  { word: 'おとこ', romaji: 'otoko', meaning: 'laki-laki' },
  { word: 'おんな', romaji: 'onna', meaning: 'perempuan' },
  { word: 'こども', romaji: 'kodomo', meaning: 'anak-anak' },
  { word: 'ともだち', romaji: 'tomodachi', meaning: 'teman' },
  { word: 'せんせい', romaji: 'sensei', meaning: 'guru' },
  { word: 'がくせい', romaji: 'gakusei', meaning: 'pelajar' },
  { word: 'しごと', romaji: 'shigoto', meaning: 'pekerjaan' },
  { word: 'いえ', romaji: 'ie', meaning: 'rumah' },
  { word: 'まち', romaji: 'machi', meaning: 'kota' },
  { word: 'くに', romaji: 'kuni', meaning: 'negara' },
  { word: 'ほん', romaji: 'hon', meaning: 'buku' },
  { word: 'えんぴつ', romaji: 'enpitsu', meaning: 'pensil' },
  { word: 'かみ', romaji: 'kami', meaning: 'kertas' },
  { word: 'くるま', romaji: 'kuruma', meaning: 'mobil' },
  { word: 'でんしゃ', romaji: 'densha', meaning: 'kereta' },
  { word: 'ひこうき', romaji: 'hikouki', meaning: 'pesawat' },
  { word: 'たべもの', romaji: 'tabemono', meaning: 'makanan' },
  { word: 'のみもの', romaji: 'nomimono', meaning: 'minuman' },
  { word: 'ごはん', romaji: 'gohan', meaning: 'nasi' },
  { word: 'さかな', romaji: 'sakana', meaning: 'ikan' },
  { word: 'にく', romaji: 'niku', meaning: 'daging' },
  { word: 'くだもの', romaji: 'kudamono', meaning: 'buah-buahan' },
  { word: 'やさい', romaji: 'yasai', meaning: 'sayuran' },
  { word: 'おちゃ', romaji: 'ocha', meaning: 'teh' },
  { word: 'あさ', romaji: 'asa', meaning: 'pagi' },
  { word: 'ひる', romaji: 'hiru', meaning: 'siang' },
  { word: 'よる', romaji: 'yoru', meaning: 'malam' },
  { word: 'きょう', romaji: 'kyou', meaning: 'hari ini' },
  { word: 'あした', romaji: 'ashita', meaning: 'besok' },
  { word: 'きのう', romaji: 'kinou', meaning: 'kemarin' },
  { word: 'おかね', romaji: 'okane', meaning: 'uang' },
  { word: 'でんわ', romaji: 'denwa', meaning: 'telepon' },
  { word: 'とけい', romaji: 'tokei', meaning: 'jam' },
  { word: 'めがね', romaji: 'megane', meaning: 'kacamata' },
  { word: 'かばん', romaji: 'kaban', meaning: 'tas' },
  { word: 'くつ', romaji: 'kutsu', meaning: 'sepatu' },
  { word: 'ふく', romaji: 'fuku', meaning: 'baju' },
  { word: 'かお', romaji: 'kao', meaning: 'wajah' },
  { word: 'あたま', romaji: 'atama', meaning: 'kepala' },
  { word: 'て', romaji: 'te', meaning: 'tangan' },
  { word: 'あし', romaji: 'ashi', meaning: 'kaki' },
  { word: 'め', romaji: 'me', meaning: 'mata' },
  { word: 'みみ', romaji: 'mimi', meaning: 'telinga' },
  { word: 'くち', romaji: 'kuchi', meaning: 'mulut' },
  { word: 'こころ', romaji: 'kokoro', meaning: 'hati' },
  { word: 'なまえ', romaji: 'namae', meaning: 'nama' },
  { word: 'にほん', romaji: 'nihon', meaning: 'Jepang' }
];

// --- LEVEL 3: Sentences (35 sentences) ---
const SENTENCES = [
  { sentence: 'わたしはがくせいです', romaji: 'watashi wa gakusei desu', meaning: 'Saya adalah pelajar' },
  { sentence: 'これはほんです', romaji: 'kore wa hon desu', meaning: 'Ini adalah buku' },
  { sentence: 'おはようございます', romaji: 'ohayou gozaimasu', meaning: 'Selamat pagi' },
  { sentence: 'こんにちは', romaji: 'konnichiwa', meaning: 'Selamat siang' },
  { sentence: 'こんばんは', romaji: 'konbanwa', meaning: 'Selamat malam' },
  { sentence: 'ありがとうございます', romaji: 'arigatou gozaimasu', meaning: 'Terima kasih' },
  { sentence: 'すみません', romaji: 'sumimasen', meaning: 'Maaf / Permisi' },
  { sentence: 'おなまえはなんですか', romaji: 'onamae wa nan desu ka', meaning: 'Siapa nama Anda?' },
  { sentence: 'にほんごをべんきょうしています', romaji: 'nihongo wo benkyou shite imasu', meaning: 'Saya sedang belajar bahasa Jepang' },
  { sentence: 'いただきます', romaji: 'itadakimasu', meaning: 'Selamat makan (sebelum makan)' },
  { sentence: 'ごちそうさまでした', romaji: 'gochisousama deshita', meaning: 'Terima kasih atas makanannya' },
  { sentence: 'おげんきですか', romaji: 'ogenki desu ka', meaning: 'Apa kabar?' },
  { sentence: 'はいげんきです', romaji: 'hai genki desu', meaning: 'Ya, saya baik-baik saja' },
  { sentence: 'さようなら', romaji: 'sayounara', meaning: 'Selamat tinggal' },
  { sentence: 'がんばってください', romaji: 'ganbatte kudasai', meaning: 'Semangat!' },
  { sentence: 'わたしはにほんじんです', romaji: 'watashi wa nihonjin desu', meaning: 'Saya orang Jepang' },
  { sentence: 'これはいくらですか', romaji: 'kore wa ikura desu ka', meaning: 'Berapa harga ini?' },
  { sentence: 'トイレはどこですか', romaji: 'toire wa doko desu ka', meaning: 'Di mana toilet?' },
  { sentence: 'みずをください', romaji: 'mizu wo kudasai', meaning: 'Tolong beri air' },
  { sentence: 'にほんごがすきです', romaji: 'nihongo ga suki desu', meaning: 'Saya suka bahasa Jepang' },
  { sentence: 'たなかさんはせんせいです', romaji: 'tanaka san wa sensei desu', meaning: 'Tanaka adalah guru' },
  { sentence: 'まいにちべんきょうします', romaji: 'mainichi benkyou shimasu', meaning: 'Saya belajar setiap hari' },
  { sentence: 'あしたがっこうにいきます', romaji: 'ashita gakkou ni ikimasu', meaning: 'Besok saya pergi ke sekolah' },
  { sentence: 'ともだちとあそびます', romaji: 'tomodachi to asobimasu', meaning: 'Bermain dengan teman' },
  { sentence: 'ねこがすきです', romaji: 'neko ga suki desu', meaning: 'Saya suka kucing' },
  { sentence: 'さむいですね', romaji: 'samui desu ne', meaning: 'Dingin ya' },
  { sentence: 'あついですね', romaji: 'atsui desu ne', meaning: 'Panas ya' },
  { sentence: 'おいしいです', romaji: 'oishii desu', meaning: 'Enak' },
  { sentence: 'たのしいです', romaji: 'tanoshii desu', meaning: 'Menyenangkan' },
  { sentence: 'わたしのかぞくはよにんです', romaji: 'watashi no kazoku wa yonin desu', meaning: 'Keluarga saya empat orang' },
  { sentence: 'えいがをみます', romaji: 'eiga wo mimasu', meaning: 'Menonton film' },
  { sentence: 'おんがくをききます', romaji: 'ongaku wo kikimasu', meaning: 'Mendengarkan musik' },
  { sentence: 'ごはんをたべます', romaji: 'gohan wo tabemasu', meaning: 'Makan nasi' },
  { sentence: 'おちゃをのみます', romaji: 'ocha wo nomimasu', meaning: 'Minum teh' },
  { sentence: 'はじめまして', romaji: 'hajimemashite', meaning: 'Salam kenal' }
];
